### ISSUE TITLE
Cannot cancel DelayedJob via ActiveJob id

### ISSUE THREAD

**Issue by thisismydesign** [y-yagi/activejob-cancel#25]
It's not possible as currently written: https://github.com/y-yagi/activejob-cancel/blob/407990cf3a5211f25499eac436063fd50b237214/lib/active_job/cancel/queue_adapters/delayed_job_adapter.rb#L8-L16

See: https://stackoverflow.com/questions/29855768/rails-4-2-get-delayed-job-id-from-active-job

So for DelayedJob only `cancel_by` is supported. It would be better to remove the faulty `cancel` implementation altogether. Perhaps raise a not implemented error there.

**Comment by y-yagi** [comment]
I'm not sure your issue. The cancel test passed. 
https://github.com/y-yagi/activejob-cancel/blob/407990cf3a5211f25499eac436063fd50b237214/test/queue_adapters/delayed_job_adapter_test.rb#L29-L39 

Could you elaborate a more detailed explanation?

**Comment by thisismydesign** [comment]
My bad, looked at the `find_job` and it uses `handler` instead of `id`. I guess the actual reason was the other one I reported but I attributed it to something else here, sorry.
