### ISSUE TITLE
Undefined method default_queue_name when cancel job

### ISSUE THREAD

**Issue by javierav** [y-yagi/activejob-cancel#30]
When I run this code:

```
job = TestJob.set(wait_until: DateTime.current + 10.days).perform_later
model.update(job_id: job.job_id)

# ...

TestJob.cancel(model.job_id)
```

I get the following error:

```
undefined method `default_queue_name' for Class:Class Did you mean? default_metric_name_code


/GEM_ROOT/gems/activejob-6.0.3.4/lib/active_job/queue_name.rb:57→ block (2 levels) in <module:QueueName>
/GEM_ROOT/bundler/gems/activejob-cancel-fc0e9ce8db96/lib/active_job/cancel/queue_adapters/sidekiq_adapter.rb:8→ cancel
/GEM_ROOT/bundler/gems/activejob-cancel-fc0e9ce8db96/lib/active_job/cancel.rb:24→ cancel
```

This error is produced when internally calls to `TestJob.queue_name` thats returns a default lambda thats is evaluated in `https://github.com/y-yagi/activejob-cancel/blob/fc0e9ce8db965740694cab66c3117fd200131f0a/lib/active_job/cancel/queue_adapters/sidekiq_adapter.rb#L8` instead of be evaluated in the job instance as rails expected.

* rails (6.0.3.4)
* activejob-cancel (fc0e9ce8db965740694cab66c3117fd200131f0a)

**Comment by y-yagi** [comment]
Thanks for your report! I fixed the issue and released a new version https://rubygems.org/gems/activejob-cancel/versions/0.3.1
